# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"  # For Node.js projects using npm
    directory: "/"  # Location of package manifests (package.json)
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10  # Limit number of open PRs at any time
    
  # If you're also using GitHub Actions, you might want to add:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
