name: Pre-Release on Push

on:
  push:
    branches: [ main ]

env:
  RELEASE_TAG: pre-${{ github.run_number }}-${{ github.sha }}

permissions:
  contents: write

jobs:
  prerelease:
    name: Build and Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Restore Next.js build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: '1'

      - name: Package build artifacts
        run: |
          mkdir -p dist-package
          cp -r public dist-package/public || true
          cp -r .next dist-package/.next || true
          cp package.json package-lock.json next.config.ts tsconfig.json dist-package/ || true
          cd dist-package
          zip -r ../web-build.zip . > /dev/null

      - name: Generate changelog
        shell: bash
        run: |
          set -euo pipefail
          SERVER_URL="${GITHUB_SERVER_URL:-https://github.com}"
          REPO="${GITHUB_REPOSITORY}"
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "## Changes" > release_notes.md
          if [ -z "$LAST_TAG" ]; then
            echo "_Initial pre-release; showing last 50 commits._" >> release_notes.md
            LOG=$(git log --pretty=format:'%h|%s|%an' -n 50)
          else
            echo "_Changes since $LAST_TAG._" >> release_notes.md
            LOG=$(git log "$LAST_TAG"..HEAD --pretty=format:'%h|%s|%an')
          fi
          echo "" >> release_notes.md

          gen_section() { # title pattern
            local TITLE="$1"
            local PATTERN="$2"
            local BODY
            BODY=$(echo "$LOG" | grep -E "\|$PATTERN" || true)
            if [ -n "$BODY" ]; then
              echo "### $TITLE" >> release_notes.md
              echo "$BODY" | while IFS='|' read -r h s a; do echo "- [**$h**](${SERVER_URL}/${REPO}/commit/$h) $s ($a)"; done >> release_notes.md
              echo "" >> release_notes.md
            fi
          }

          gen_section "Features" 'feat(\(|:|!)'
          gen_section "Fixes" 'fix(\(|:|!)'
          gen_section "Performance" 'perf(\(|:|!)'
          gen_section "Docs" 'docs(\(|:|!)'
          gen_section "Chores" 'chore(\(|:|!)'

          # Others = everything not matched above
          OTHER=$(echo "$LOG" | grep -Ev "\|(feat|fix|perf|docs|chore)(\(|:|!)" || true)
          if [ -n "$OTHER" ]; then
            echo "### Others" >> release_notes.md
            echo "$OTHER" | while IFS='|' read -r h s a; do echo "- [**$h**](${SERVER_URL}/${REPO}/commit/$h) $s ($a)"; done >> release_notes.md
            echo "" >> release_notes.md
          fi

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Pre-Release ${{ github.run_number }} (${{ github.sha }})
          body_path: release_notes.md
          prerelease: true
          files: |
            web-build.zip

  tauri-windows:
    name: Tauri Windows Portable
    needs: prerelease
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Generate Tauri icons from SVG
        shell: pwsh
        run: |
          if (Test-Path out/icon.svg) { $src = 'out/icon.svg' } else { $src = 'public/icon.svg' }
          if (-not (Test-Path $src)) { throw "icon.svg not found at $src" }
          npx tauri icon $src -o src-tauri/icons | cat

      - name: Build static web (export)
        run: npm run tauri:export

      - name: Build Tauri (portable app)
        run: npm run tauri:build

      - name: Package Windows portable
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Recurse -Path src-tauri/target/release -Filter *.exe | Select-Object -First 1
          if (-not $exe) { throw "No Windows executable found" }
          Compress-Archive -Path $exe.FullName -DestinationPath win-portable.zip -Force

      - name: Upload to Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            win-portable.zip

  tauri-linux:
    name: Tauri Linux Portable
    needs: prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf
          sudo apt-get install -y libwebkit2gtk-4.1-dev || sudo apt-get install -y libwebkit2gtk-4.0-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Generate Tauri icons from SVG
        run: |
          set -e
          SRC="out/icon.svg"
          if [ ! -f "$SRC" ]; then SRC="public/icon.svg"; fi
          if [ ! -f "$SRC" ]; then echo "icon.svg not found" && exit 1; fi
          npx tauri icon "$SRC" -o src-tauri/icons | cat

      - name: Build static web (export)
        run: npm run tauri:export

      - name: Build Tauri (portable app)
        run: npm run tauri:build

      - name: Package Linux portable
        run: |
          set -e
          BIN=$(ls -1 src-tauri/target/release/app 2>/dev/null || true)
          if [ -z "$BIN" ]; then BIN=$(ls -1 src-tauri/target/release/* | head -n 1); fi
          if [ -z "$BIN" ]; then echo "No Linux binary found" && exit 1; fi
          zip -j linux-portable.zip "$BIN" > /dev/null

      - name: Upload to Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            linux-portable.zip

  tauri-android:
    name: Tauri Android (Debug APK)
    needs: prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          yes | sdkmanager --licenses > /dev/null
          sdkmanager --install "platform-tools" "platforms;android-33" "platforms;android-34" "build-tools;34.0.0" "build-tools;33.0.2" "cmake;3.22.1" "ndk;25.1.8937393"

      - name: Set Android env (NDK_HOME, ANDROID_HOME)
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          NDK_DIR=$(ls -1d "$ANDROID_SDK_ROOT"/ndk/* | sort -V | tail -n 1)
          if [ -z "$NDK_DIR" ]; then echo "NDK not found under $ANDROID_SDK_ROOT/ndk" && exit 1; fi
          echo "NDK_HOME=$NDK_DIR" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$NDK_DIR" >> $GITHUB_ENV

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Android Rust targets
        run: |
          rustup target add aarch64-linux-android

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Generate Tauri icons from SVG
        run: |
          set -e
          SRC="out/icon.svg"
          if [ ! -f "$SRC" ]; then SRC="public/icon.svg"; fi
          if [ ! -f "$SRC" ]; then echo "icon.svg not found" && exit 1; fi
          npx tauri icon "$SRC" -o src-tauri/icons | cat

      - name: Build static web (export)
        run: npm run tauri:export

      - name: Init Android project
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
          NDK_HOME: ${{ env.NDK_HOME }}
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          npx tauri android init --ci
          test -d src-tauri/gen/android || (echo "Init did not generate project" && exit 1)

      - name: Verify Android project exists
        run: |
          test -d src-tauri/gen/android || (ls -la src-tauri/gen || true; echo "Android project missing"; exit 1)

      - name: Build Android (debug)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
          NDK_HOME: ${{ env.NDK_HOME }}
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          npx tauri android build --debug --ci
          mkdir -p android-dist
          find src-tauri/gen/android -type f -name "*.apk" -print -exec cp {} android-dist/ \;
          zip -r android-apk.zip android-dist > /dev/null

      - name: Build Android (debug)
        run: npx tauri android build --debug

      - name: Package Android APK(s)
        run: |
          set -e
          mkdir -p android-dist
          find src-tauri/target -type f -name "*.apk" -print -exec cp {} android-dist/ \;
          if [ -z "$(ls -A android-dist)" ]; then echo "No APKs found" && exit 1; fi
          zip -r android-apk.zip android-dist > /dev/null

      - name: Upload to Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            android-apk.zip
